# Generated by Django 2.1.1 on 2018-10-05 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internships', models.CharField(default=None, max_length=1000)),
                ('placements', models.CharField(default=None, max_length=1000)),
                ('company_unam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
