# Generated by Django 2.1.1 on 2018-10-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('contact', models.IntegerField(max_length=10)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('pic_path', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
