# Generated by Django 2.1.1 on 2018-10-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.FloatField(),
        ),
    ]
