# Generated by Django 2.1.1 on 2018-10-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_academicprofile_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprofile',
            name='hsc',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='academicprofile',
            name='ssc',
            field=models.CharField(max_length=5),
        ),
    ]
