# Generated by Django 2.1.1 on 2018-10-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20181005_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('pic_path', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=500)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=20)),
                ('github', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=500)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=20)),
                ('rate', models.CharField(max_length=5)),
                ('student', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
